name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-32

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitLab credentials
        run: |
          echo "registry.gitlab.com:
            username: ${{ secrets.GITLAB_USERNAME }}
            password: ${{ secrets.GITLAB_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Publish package to GitLab
        run: npm publish --registry=https://registry.gitlab.com
